### ISSUE TITLE
Broken Messages

### ISSUE THREAD

**Issue by srbarba** [Magestore/Bannerslider-Magento2#16]
When I put the bannerslider at Home-Content-Top it breaks the instant message of magento.
If you add a product, the messages appear like a flash and is immediately deleted from view.

It seems some conflict with javaScript, because the messages container still there.

Otherwise, at product-content-top it works fine...

**Comment by NicolasAndersen** [comment]
Could you please send me some photo or send me link of your live site?

**Comment by srbarba** [comment]
Hi, 
I can't take a photo because the message disappear so fast. 
But you can see at your home demo page:
http://demo-magento2.magestore.com/banner-slider/

When you add a product from home page, the page reload and display a message. How your demo works bit slowly, the message takes a time to appear and disappear. If you see de message.js, which runs the code to display and hide the message, it have a delay of 5000ms to hide the message. If you count the time that your demo takes to hide the message, it oscillate between 1-2sec, depends of the velocity it load the files.
Otherwise, if you add the product at the product page, it loads correctly. 

I can't say where is the problem, but I guess it can be the order where the files are loaded.

By the way, thank you for this extension. Great work!

**Comment by srbarba** [comment]
Looking at chrome devtools, I see your module is sending some empty message.
I can't find where it happens, because it only happens at home page.
Maybe you know something about it.

**Comment by twistedindustries** [comment]
I am also trying to track this down... I am searching through the code and don't find where its setting messsages.

**Comment by twistedindustries** [comment]
Here is a fix for now if you don't care about tracking impressions:  simply remove data-mage-init='{"magestore/impress": {"url": "<?php echo $this->getUrl("bannerslider/index/impress") ?>", "slider_id": "<?php echo $slider->getId() ?>"}}' from your slider code.  Hopefully devs will find the real fix soon.
