### ISSUE TITLE
error when adding new banner

### ISSUE THREAD

**Issue by ad1rie1** [Magestore/Bannerslider-Magento2#3]
Hello, i'm set admin interface in french, when i save my new banner, 
the error happend : 
DateTime::__construct(): Failed to parse time string (30/12/2015 09:09) at position 0 (3): Unexpected character
Something went wrong while saving the banner.

Can you see for fix that ?

**Comment by NicolasAndersen** [comment]
I have fixed this issue. Please check it again.
