### ISSUE TITLE
When I enable slider on CMS Page, I get blank page

### ISSUE THREAD

**Issue by jernejh** [Magestore/Bannerslider-Magento2#32]
I installed Bannerslider successfully on magento2. When I enable slider and copy snippet for showing slider on a CMS Page, I get blank page with the following source code right after script section:

`<div class="magestore-bannerslider-standard" data-mage-init='{"magestore/impress": {"url": "<br />
<b>Fatal error</b>:  Cannot access protected property Magestore\Bannerslider\Block\SliderItem::$_request in <b>%MAGENTO_INSTALL_ROOT_FOLDER%\vendor\magento\framework\View\TemplateEngine\Php.php</b> on line <b>110</b><br />`

**Comment by FrameriMatt** [comment]
I've been getting the same issue too.

**Comment by itdint** [comment]
#1 on this error.  I've tried everything I can think off..  I just get this in the error log..  

FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot access protected property Magestore\Bannerslider\Block\SliderItem::$_request in /data/mage2/vendor/magento/framework/View/TemplateEngine/Php.php on line 110" while reading response header from upstream

Any ideas on this?

**Comment by edenduong** [comment]
Hello there,

Have a nice day. Thank you for your feedback.
I have just fixed this problem. Please down the new source code and check it again.

Thank you very much.

**Comment by jernejh** [comment]
Hero of a day. Now it works. Thank you.

Best, Jernej

**Comment by itdint** [comment]
Excellent.. Thank you for the quick turnaround.
