### ISSUE TITLE
error on preview Slider Evolution Minimalist

### ISSUE THREAD

**Issue by ad1rie1** [Magestore/Bannerslider-Magento2#4]
hello, 
This error was append when i want to display Slider Evolution Minimalist preview :
:443/static/adminhtml/Magento/backend/fr_FR/Magestore_Bannerslider/js/jquery/slider/jquery-slider-min.js:16 Uncaught TypeError: Cannot read property 'msie' of undefined

127.0.0.1/:266 Uncaught TypeError: $(...).slideshow is not a function

Can you see for fix that ?

**Comment by NicolasAndersen** [comment]
I have fixed this issue. Please check it again. Make sure your Magento 2 is in developer mode. 
Use this command to set developer mode in Magento 2 : 
php bin/magento deploy:mode:set developer
