### ISSUE TITLE
Error on page create new slider

### ISSUE THREAD

**Issue by ad1rie1** [Magestore/Bannerslider-Magento2#5]
hello, 
when i want to create a new slyder, on error happend : 
ParseError: Unrecognised input
in zebra_tooltips.css on line 23, column 73:

22    *margin-right: 0;
23    _width:expression(document.body.clientWidth > 250 ? '250px': 'auto'); /* max-width for IE6 */
24}

Can you fix that ?

**Comment by NicolasAndersen** [comment]
I have fixed this issue. Please check it again.
