### ISSUE TITLE
Js files are not including from correct path

### ISSUE THREAD

**Issue by Erchiragdodia** [Magestore/Bannerslider-Magento2#6]
After successfully installed and configure module on frontside i'm getting jquery file errors in console like

GET http://localhost/magento2-develop/pub/static/frontend/Magento/luma/en_US/magestore/evolutionslider.js 

Magento is trying to search file from above location, as per the module it should search for the file in to
http://localhost/magento2-develop/pub/static/frontend/Magento/luma/en_US/Magestore_Bannerslider/js/evolutionslider.js path 

why its looking in to wrong path?

All js files are already generated in 
pub\static\frontend\Magento\luma\en_US\Magestore_Bannerslider\js  path

**Comment by blankapham** [comment]
May be your installation is in default mode. Please change to developer mode by using this command:
php bin/magento deploy:mode:set developer (window server) or bin/magento deploy:mode:set developer (linux)
After change to developer mode, static files will be generated after reloading page.
