### ISSUE TITLE
Lỗi 500 khi click vào submenu.

### ISSUE THREAD

**Issue by HaiDang15** [Magestore/Bannerslider-Magento2#8]
Cho mình hỏi trong sub menu : Manage Sliders , mình thấy bạn có add 1 action = "bannerslideradmin/slider/" , mình có tìm đến class Index.php theo đường dẫn : Controller/Adminhtml/Slider/Index.php và thấy class này extends lại chính nó . Vậy cho mình hỏi tại sao trong class này ( Index.php ) nó lại kế thừa lại chính nó mà ko phải 1 lớp nào đó trong core của Magento ( chẳng hạn : \Magento\Backend\App\Action ) . Mình có làm theo như code của bạn nhưng nhận được lỗi : " 500 - Server error " .

**Comment by NicolasAndersen** [comment]
Bạn chú ý nhìn kỹ, lớp \Magestore\Bannerslider\Controller\Adminhtml\Slider\Index có namespace là Magestore\Bannerslider\Controller\Adminhtml\Slider và kế thừa từ lớp \Magestore\Bannerslider\Controller\Adminhtml\Slider chứ không phải kế thừa chính nó đâu nhé.

Bạn để ý các lớp:
namespace Magestore\Bannerslider\Controller\Adminhtml;
abstract class AbstractAction extends \Magento\Backend\App\Action
-------------------------------------------------------------------------------------------------------------------

namespace Magestore\Bannerslider\Controller\Adminhtml;
abstract class Slider extends \Magestore\Bannerslider\Controller\Adminhtml\AbstractAction
-------------------------------------------------------------------------------------------------------------------

namespace Magestore\Bannerslider\Controller\Adminhtml\Slider;
class Index extends \Magestore\Bannerslider\Controller\Adminhtml\Slider

Như vậy thì lớp \Magestore\Bannerslider\Controller\Adminhtml\Slider\Index vẫn là lớp con cháu của lớp \Magento\Backend\App\Action nhé

**Comment by HaiDang15** [comment]
Cảm ơn bạn nhiều .
