### ISSUE TITLE
Ending time: High values of ending time get truncated 

### ISSUE THREAD

**Issue by swrdfish** [Magestore/Bannerslider-Magento2#89]
If I try to set a ending time of say 1st January 2115, the ending time is set to 25th November 1978.

Might be some issue with the model or with a variable length.

**Comment by sv63rus** [comment]
Maybe it is 2038 problem ?  https://en.wikipedia.org/wiki/Year_2038_problem

**Comment by swrdfish** [comment]
@sv63rus thanks for the insight. That indeed is possible, I tried it in a different machine and things worked perfectly. So my guess is that the issue is related to the database. I'll close the issue after checking it in the system that originally had the problem.

**Comment by swrdfish** [comment]
it indeed was the 2038 problem.
