### ISSUE TITLE
Undefined class constant error when custom template

### ISSUE THREAD

**Issue by chombe** [Magestore/Bannerslider-Magento2#9]
Hi

This is really great extension, i am impressed. Congratulation....

One little thing, line 184 it should be self::STYLESLIDE_CUSTOM_TEMPLATE
file https://github.com/Magestore/Bannerslider-Magento2/blob/master/app/code/Magestore/Bannerslider/Block/SliderItem.php

Happy New Year

**Comment by NicolasAndersen** [comment]
Thanks for your feedback! I have solved that issue. 

Happy New Year!
